services:
  web:
    build: .
    container_name: greatkart_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: greatkart_db
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      DATABASE_URL: postgres://postgres:1234@db:5432/greatkartdb
      CELERY_BROKER_URL: redis://redis:6379/0

    depends_on:
      - db
      - redis

  celery:
    build: .
    container_name: greatkart_celery
    command: celery -A greatkart worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgres://postgres:1234@db:5432/greatkartdb
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: greatkart_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: greatkart_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: greatkart_redis
    ports:
      - "6379:6379"

  pgadmin:
    image: dpage/pgadmin4
    container_name: greatkart_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: zeeshansheikh0313@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Zeeshan0313@
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  pgdata:
